# Generated by Django 3.2.4 on 2021-08-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('books', models.ManyToManyField(related_name='book', to='books.Book')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
