# Generated by Django 3.2.4 on 2021-08-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
